const baseURL = 'https://xmldata.qrz.com/xml/current/';

const mors = {
  "A": "● –",
  "B": "– ● ● ●",
  "C": "– ● – ●",
  "D": "– ● ●",
  "E": "●",
  "F": "● ● – ●",
  "G": "– – ●",
  "H": "● ● ● ●",
  "I": "● ●",
  "J": "● – – –",
  "K": "– ● –",
  "L": "● – ● ●",
  "M": "– –",
  "N": "– ●",
  "O": "– – –",
  "P": "● – – ●",
  "Q": "– – ● –",
  "R": "● – ●",
  "S": "● ● ●",
  "T": "–",
  "U": "● ● –",
  "V": "● ● ● –",
  "W": "● – –",
  "Y": "– ● – –",
  "Z": "– – ● ●",
  "1": "● – – – –",
  "2": "● ● – – –",
  "3": "● ● ● – –",
  "4": "● ● ● ● –",
  "5": "● ● ● ● ●",
  "6": "– ● ● ● ●",
  "7": "– – ● ● ●",
  "8": "– – – ● ●",
  "9": "– – – – ●",
  "0": "– – – – –"
}

const fonetik = {
  "A": "Alfa",
  "B": "Bravo",
  "C": "Charlie",
  "D": "Delta",
  "E": "Echo",
  "F": "Foxtrott",
  "G": "Golf",
  "H": "Hotel",
  "I": "India",
  "J": "Juliett",
  "K": "Kilo",
  "L": "Lima",
  "M": "Mike",
  "N": "November",
  "O": "Oscar",
  "P": "Papa",
  "Q": "Quebec",
  "R": "Romeo",
  "S": "Sierra",
  "T": "Tango",
  "U": "Uniform",
  "V": "Victor",
  "W": "Whiskey",
  "Y": "Yankee",
  "Z": "Zulu",
  "1": "Bir",
  "2": "İki",
  "3": "Üç",
  "4": "Dört",
  "5": "Beş",
  "6": "Altı",
  "7": "Yedi",
  "8": "Sekiz",
  "9": "Dokuz",
  "0": "Sıfır" 
}

export {baseURL, fonetik, mors};